### ISSUE TITLE
Do you have IUPred2A?

### ISSUE THREAD

**Issue by victorconan** [miguelarbesu/IUPipe#1]
Thanks for creating this tool! I wonder if you have IUPred2A. The website seems to be down as of Aug 17 2022. It would be great if you happen to have the python library of IUPred2A.

Thanks!

**Comment by miguelarbesu** [comment]
Hi @victorconan , thanks for your message!
Unfortunately I do not have a copy of the software, but surely the authors will be happy to share it if you contact them directly :)
